[package]
name = "voxelizer"
version = "0.1.0"
authors = ["Kris <viestards746@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
tobj = "2.0.4"
byteorder = "1.4.3"
rand = "0.8.3"